default:
  image: lopoeisr/ubuntu-make-clang:18

stages:
  - build
  - preparation
  - test

build-job:
  tags:
    - c
    - c++
    - liburing
    - privileged
  stage: build
  script:
    - make libs
  artifacts:
    paths:
      - threadpool/bin/
      - threadpool/build/
      - threadpool/lib/
      - saurion/bin/
      - saurion/build/
      - saurion/lib/

preparation-job:
  stage: preparation
  script:
    - make gtest
  artifacts:
    paths:
      - gtest/

test-job:
  tags:
    - c
    - c++
    - liburing
    - privileged
  stage: test
  script:
    - make tests
  artifacts:
    paths:
      - threadpool/bin/
      - threadpool/build/
      - threadpool/lib/
      - saurion/bin/
      - saurion/build/
      - saurion/lib/
