name: C Project CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:  # Permite ejecutar el workflow manualmente
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      release_name:
        description: 'Release name'
        required: true

jobs:
  build-and-test-gcc:
    name: Build, Test and Package with GCC
    runs-on: ubuntu-latest
    container: 
      image: lopoeisr/ubuntu-make-gcc
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare environment with make gtest
      run: make gtest

    - name: Run tests
      run: make tests

    - name: Run valgrind
      run: make valgrind

    - name: Create libraries
      run: make clean && make libs && make docs

    - name: Package libraries
      run: tar -czvf gcc-libs-n-docs.tar.gz libs docs

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gcc-libs-n-docs
        path: gcc-libs-n-docs.tar.gz

  build-and-test-clang:
    name: Build, Test and Package with Clang
    runs-on: ubuntu-latest
    container:
      image: lopoeisr/ubuntu-make-clang
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare environment with make gtest
      run: make gtest

    - name: Run tests
      run: make tests

    - name: Run valgrind
      run: make valgrind

    - name: Create libraries
      run: make clean && make libs && make docs

    - name: Package libraries
      run: tar -czvf clang-libs-n-docs.tar.gz libs docs

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: clang-libs-n-docs
        path: clang-libs-n-docs.tar.gz

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-and-test-gcc, build-and-test-clang]

    steps:
    - name: Download GCC artifact
      uses: actions/download-artifact@v3
      with:
        name: gcc-libs-n-docs

    - name: Download Clang artifact
      uses: actions/download-artifact@v3
      with:
        name: clang-libs-n-docs

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        release_name: ${{ github.event.inputs.release_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          Release for ${{ github.event.inputs.release_name }}
          - GCC compiled libraries
          - Clang compiled libraries

    - name: Upload GCC libraries to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: gcc-libs-n-docs.tar.gz
        asset_name: gcc-libs-n-docs.tar.gz
        asset_content_type: application/gzip

    - name: Upload Clang libraries to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: clang-libs-n-docs.tar.gz
        asset_name: clang-libs-n-docs.tar.gz
        asset_content_type: application/gzip

