name: Push

on:
  push:
    branches: ["*"]

  workflow_dispatch:  # Permite ejecutar el workflow manualmente
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      release_name:
        description: 'Release name'
        required: true

jobs:
  use-reusable-workflow:
    uses: ./.scaffold/workflows/main.yml
    with:
      after_prepare: |
        - name: Upload dependencies
          uses: actions/upload-artifact@v3
          with:
            name: dependencies
            path: |
              ./saurion/scripts/client
              ./saurion/scripts/server
      before_tests: |
        - name: Create directories and move scripts
          run: |
            mkdir -p saurion/scripts
            mv client saurion/scripts/
            mv server saurion/scripts/
            chmod +x saurion/scripts/client
            chmod +x saurion/scripts/server

